version: "3.5"

services:
  web:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
      target: production
    restart: "always"
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: mongo
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
